language: node_js
node_js:
  - "node"

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

script:
  - ./index.js -o test/rendered.css test/include.scss
  - git diff --exit-code
