language: node_js
node_js:
  - "node"

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

before_script:
  - npm install

script:
  - css-sniper -o test/rendered.css test/include.scss
  - git diff --exit-code
